---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Presigned Post API

Parameters:
  Bucket:
    Type: String

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LambdaInvokeLoggingAndS3Object
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - s3:*Object
            Resource: !Join
              - ''
              - - "arn:aws:s3:::"
                - !Ref Bucket
                - "/*"
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: arn:aws:lambda:*:*:*
            
  LambdaApiGatewayS3PresignedPostFunctionExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt S3PresignedPostFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref S3PresignedPostApiGateway
          - "/*/*"

  S3PresignedPostApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./s3-presigned-post-api.yaml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref S3PresignedPostFunction
  
  S3PresignedPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: s3-presigned-post.getPresignedPostData
      MemorySize: 256
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs14.x
      Timeout: 30
      Environment:
        Variables:
          BUCKET: !Ref Bucket
          FILES_KEY: files/
          MIN_FILE_SIZE_BYTES: 100
          MAX_FILE_SIZE_BYTES: 100000000
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref S3PresignedPostApiGateway
            Path: /api/v1/files
            Method: POST

Outputs:
  S3PresignedPostApiGatewayConsoleUrl:
    Description: Console URL for the API Gateway API's Stage.
    Value: !Join
      - ''
      - - https://
        - !Ref AWS::Region
        - ".console.aws.amazon.com/apigateway/home?region="
        - !Ref AWS::Region
        - "#/apis/"
        - !Ref S3PresignedPostApiGateway
        - "/stages/prod"

  S3PresignedPostApiUrl:
    Description: Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Join
      - ''
      - - https://
        - !Ref S3PresignedPostApiGateway
        - ".execute-api."
        - !Ref AWS::Region
        - ".amazonaws.com/prod/"